---
- hosts: all
  tasks:
    - name: cleaning files
      shell: sudo rm -rf ~/test-website

    - name: pull
      shell: sudo git clone https://github.com/khushi-carpenter-itp/test-website.git
      
    - name: docker kill
      shell: sudo docker stop ansapp || true && sudo docker rm -f ansapp || true
    
    - name: docker build
      shell: sudo docker build -t khushi3008/ansapp ~/test-website/
      
    - name: docker run 
      shell:  sudo docker run -it -d --name ansapp -p 3100:80 khushi3008/ansapp
