---
- hosts: web123
  tasks:
    - name: cleaning files
      shell: rm -rf ~/test4

    - name: pull
      shell: git clone https://github.com/Saumil343/test4.git
      
    - name: docker kill
      shell: docker stop ansapp1 || true && docker rm ansapp1 || true
    
    - name: docker build
      shell: docker build -t saumil343/ansapp1 ~/test4/
      
    - name: docker run 
      shell: docker run -it -d --name ansapp1 -p 3100:80 saumil343/ansapp1
